# Generated by Django 3.2.8 on 2023-04-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_receiver',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
